import { readFileSync } from 'node:fs';

import { LABEL } from './directory.js';
import { fakeProvider, sign, type FakeProvider } from './directory.testkit.js';
import type { NostrEvent } from './nostr.js';
import { K_BLOB, K_IMAGE, K_TEMPLATE } from './templates.js';

/**
 * Publishers, for the tests only.
 *
 * A Template, an Image Registry entry and a Blob Record are all signed by a
 * PUBLISHER — a key with no standing in the protocol, which is why the console
 * checks its signature and nothing else about it. The signing machinery is
 * `directory.testkit.ts`'s, reused rather than copied: it is the only place in
 * the console that holds a secret key, and there should go on being one.
 *
 * Beside these there are the spec's own golden fixtures, in
 * `packages/daemon/fixtures/spec/`. Those are worth more than anything signed
 * here — they are generated by the provider's wire tests and checked by its CI,
 * so a test against them is a test against the other implementation rather
 * than against this one's opinion. `specFixture` below reads them.
 */

export type FakePublisher = FakeProvider;

export function fakePublisher(seed: string): FakePublisher {
  return fakeProvider(seed);
}

export { sign };

export interface TemplateDraft {
  readonly name: string;
  readonly version?: number;
  readonly digest?: string;
  /** Omitted gives the digest-alone form (§8.4 step 3). */
  readonly entryAddress?: string | null;
  readonly entryRelay?: string | null;
  readonly ports?: { containerPort: number; protocol?: 'tcp' | 'udp' }[];
  readonly dataPath?: string;
  readonly envFixed?: Record<string, string>;
  readonly envTenant?: string[];
  readonly minResources?: {
    cpu_millicores: number;
    memory_mb: number;
    storage_gb: number;
    gpu?: string;
  };
  /** Omitted (or `true`) offers SSH, matching every Template before this field. */
  readonly sshOffered?: boolean;
  readonly createdAt?: number;
  /** Replaces the whole content, for the "this is not a Template" cases. */
  readonly rawContent?: string;
}

export const FIXTURE_DIGEST =
  'sha256:c0a665205c6d8d1f4ee8e2e217efd7a467527df34100ca78f11cca5c17486126';

export function templateEvent(publisher: FakePublisher, draft: TemplateDraft): NostrEvent {
  const digest = draft.digest ?? FIXTURE_DIGEST;
  const entryAddress =
    draft.entryAddress === null
      ? undefined
      : (draft.entryAddress ?? `${K_IMAGE}:${publisher.pubkey}:web:1.0`);
  return sign(publisher, {
    kind: K_TEMPLATE,
    created_at: draft.createdAt ?? 1_790_000_000,
    tags: [
      ['d', draft.name],
      ['L', LABEL],
    ],
    content:
      draft.rawContent ??
      JSON.stringify({
        version: draft.version ?? 1,
        image: {
          digest,
          ...(entryAddress === undefined
            ? {}
            : {
                registry_entry: {
                  address: entryAddress,
                  // §6.2 needs the hint; `null` leaves it out, to test a Template without it.
                  ...(draft.entryRelay === null
                    ? {}
                    : { relay: draft.entryRelay ?? 'wss://relay.toon.test' }),
                },
              }),
        },
        ports: (draft.ports ?? [{ containerPort: 8080 }]).map((port) => ({
          container_port: port.containerPort,
          protocol: port.protocol ?? 'tcp',
        })),
        ...(draft.dataPath === undefined ? {} : { data_path: draft.dataPath }),
        env_fixed: draft.envFixed ?? {},
        env_tenant: draft.envTenant ?? [],
        ...(draft.minResources === undefined ? {} : { min_resources: draft.minResources }),
        ...(draft.sshOffered === false ? { ssh_offered: false } : {}),
      }),
  });
}

export interface ImageEntryDraft {
  /** `<name>:<tag>`, the `d` of an entry (§8.1). */
  readonly name?: string;
  readonly digest?: string;
  readonly blobs?: {
    digest: string;
    size: number;
    media_type?: string;
    source: Record<string, unknown>;
  }[];
  readonly createdAt?: number;
  readonly rawContent?: string;
}

export function imageEntryEvent(
  publisher: FakePublisher,
  draft: ImageEntryDraft = {}
): NostrEvent {
  const name = draft.name ?? 'web:1.0';
  const digest = draft.digest ?? FIXTURE_DIGEST;
  return sign(publisher, {
    kind: K_IMAGE,
    created_at: draft.createdAt ?? 1_790_000_000,
    tags: [
      ['d', name],
      ['x', digest.slice('sha256:'.length)],
      ['L', LABEL],
    ],
    content:
      draft.rawContent ??
      JSON.stringify({
        digest,
        media_type: 'application/vnd.oci.image.manifest.v1+json',
        blobs: draft.blobs ?? [
          {
            digest,
            size: 549,
            media_type: 'application/vnd.oci.image.manifest.v1+json',
            source: { type: 'toon-store', blob_record_txid: 'dG9vbi1zdG9yZS1tYW5pZmVzdA' },
          },
          {
            digest: `sha256:${'1'.repeat(64)}`,
            size: 2048,
            media_type: 'application/vnd.oci.image.layer.v1.tar',
            source: {
              type: 'oci',
              registry: 'registry-1.docker.io',
              repository: 'library/alpine',
            },
          },
        ],
      }),
  });
}

export interface BlobRecordDraft {
  readonly digest?: string;
  readonly size?: number;
  readonly partSize?: number;
  readonly shape?: 'inline' | 'paged' | 'both' | 'neither';
  readonly createdAt?: number;
  readonly rawContent?: string;
}

/**
 * A Blob Record whose arithmetic adds up, because the reader checks it: the
 * parts' sizes sum to `size`, and their count is the one `size` and
 * `part_size` imply (§8.2).
 */
export function blobRecordEvent(
  uploader: FakePublisher,
  draft: BlobRecordDraft = {}
): NostrEvent {
  const digest = draft.digest ?? FIXTURE_DIGEST;
  const size = draft.size ?? 235_008;
  const partSize = draft.partSize ?? 102_400;
  const count = Math.ceil(size / partSize);
  const parts = Array.from({ length: count }, (_unused, at) => ({
    txid: `part-${at}`,
    sha256: String(at + 1)
      .repeat(64)
      .slice(0, 64),
    size: at === count - 1 ? size - partSize * (count - 1) : partSize,
  }));
  const pages = [{ txid: 'page-0', sha256: 'a'.repeat(64), parts: count }];
  const shape = draft.shape ?? 'inline';

  return sign(uploader, {
    kind: K_BLOB,
    created_at: draft.createdAt ?? 1_790_000_000,
    tags: [
      ['d', digest],
      ['x', digest.slice('sha256:'.length)],
      ['L', LABEL],
    ],
    content:
      draft.rawContent ??
      JSON.stringify({
        digest,
        size,
        part_size: partSize,
        ...(shape === 'inline' || shape === 'both' ? { parts } : {}),
        ...(shape === 'paged' || shape === 'both' ? { pages } : {}),
      }),
  });
}

export function metadataEvent(
  publisher: FakePublisher,
  metadata: Record<string, unknown>,
  createdAt = 1_790_000_000
): NostrEvent {
  return sign(publisher, {
    kind: 0,
    created_at: createdAt,
    tags: [],
    content: JSON.stringify(metadata),
  });
}

/** One of the spec's golden fixtures, read from `fixtures/spec/`. */
export function specFixture(name: string): Record<string, unknown> {
  const path = new URL(`../fixtures/spec/${name}.json`, import.meta.url);
  return JSON.parse(readFileSync(path, 'utf8')) as Record<string, unknown>;
}

/** The `event` of a spec fixture, as a relay would hand it over. */
export function specEvent(name: string): NostrEvent {
  return specFixture(name).event as NostrEvent;
}
